name: "simple-net"
platform: "onnxruntime_onnx"
max_batch_size: 8

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [1, 28, 28]
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [10]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]

parameters: {
  key: "INFERENCE_MODE"
  value: {
    string_value: "true"
  }
}