# docker-compose.yml
version: '3.8'

services:
  minio:
    image: minio/minio:latest
    platform: linux/amd64
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  triton:
    image: nvcr.io/nvidia/tritonserver:23.10-py3
    platform: linux/amd64
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    command: >
      tritonserver
      --model-repository=/models
      --model-control-mode=poll
      --repository-poll-secs=30
      --exit-on-error=false
      --log-verbose=1
    volumes:
      - ./model_repository:/models
    depends_on:
      - minio

  inference-service:
    build: 
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      TRITON_URL: triton:8000  
    depends_on:
      - triton

volumes:
  minio_data: